######################################################################
# Automatically generated by qmake (3.1) Mon Dec 6 00:17:28 2021
######################################################################

QT += testlib core widgets
TEMPLATE = app
TARGET = tests
INCLUDEPATH += .
CONFIG+=sdk_no_version_check
# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
SOURCES += test.cpp ../bottom_widget.cpp ../top_widget.cpp ../logo_widget.cpp ../list_widget.cpp
HEADERS += ../bottom_widget.h ../top_widget.h ../logo_widget.h ../list_widget.h